### ISSUE TITLE
Verbose flag has stopped showing topical data

### ISSUE THREAD

**Issue by thezackm** [newrelic/nri-flex#108]
in previous releases of nri-flex, we could easily troubleshoot issues with individual config files by using a snippet like this: 
```
.\nri-flex.exe --verbose --pretty --config_file "path\to\config.yml"
```

This would output the JSON payload that was generated by the config and sent to NRDB, which made it very easy to see issues with formatting. Additionally, the actual execution of the command was listed in this output as well; which could show syntax issues being sent in things like the `run:` function.

Request that this functionality be restored to alleviate frustration, increase UX, and reduce development time for users.

ref: 
![image](https://user-images.githubusercontent.com/30831476/75595196-fc992580-5a50-11ea-9138-77a4eab6f4df.png)

**Comment by ardias** [comment]
Hi @thezackm 
Using version 1.0.0 i can get output similar to that in both macOs and Windows.
Example in windows:
![image](https://user-images.githubusercontent.com/2054195/75692606-167f7600-5ca6-11ea-9997-2f2f9f402174.png)

**Comment by thezackm** [comment]
this is from Windows v.1.0.0, downloaded from the latest release .zip [HERE](https://github.com/newrelic/nri-flex/releases/download/v1.0.0/nri-flex_1.0.0_Windows_x86_64.zip) and installed/configured on Feb 28.

Screenshot is current as of 5 min ago: 
![image](https://user-images.githubusercontent.com/30831476/75698818-fd120600-5c74-11ea-8318-af239324da86.png)


Note that I am receiving data in Insights; the Flex integration is working, the command line argument/output is the issue here.
![image](https://user-images.githubusercontent.com/30831476/75699047-60039d00-5c75-11ea-8e2d-8f2492e17285.png)

**Comment by Kav91** [comment]
@ardias as discussed in my PR #109 
@thezackm is executing his flexConfig directly from the integrations.d/ folder, it is not a config format Flex understands via the config_file arg anymore, its the infra agent config which then passes the config block to Flex but only when the agent executes it. For Flex to execute it now, it needs to be aware of the agents config format.

PR should be merged to resolve the issue.

**Comment by ardias** [comment]
@thezackm Sorry for the confusion regarding file formats. 
As @Kav91  said, you're using a format meant for the NR Infra agent and trying to use it with Flex.
We want to understand why did you try to use the Infra agent format directly with Flex. Was the documentation not clear in that regard? Was it the examples you saw that lead you to that? 

If you look at the output you got, there is an error in there. Was it not visible enough? Was the fact you still got some output, leading you to believe that it was working properly?

Regarding the data you are receiving, is that by running just Flex, like you did in the screen shot, or is it because you are also running the NR Infra agent (with the same configuration)?

**Comment by ardias** [comment]
For future reference, we've tried to make it more clear the difference between the Infra agent configuration format and Flex configuration format in these docs:

https://github.com/newrelic/nri-flex/blob/master/docs/development.md
https://github.com/newrelic/nri-flex/blob/master/docs/basic-tutorial.md

Take a look at them, and if you feel they need changes let us know.
Closing this for now.
