### ISSUE TITLE
Simplify custom_attributes & add_attribute

### ISSUE THREAD

**Issue by Kav91** [newrelic/nri-flex#199]
Suggestion to simplify these 2 capabilities. Per internal discussion: https://newrelic.slack.com/archives/CPVCA6Y86/p1593643334253500

They share similar purpose, but `add_attribute` has more functionality, but doesn't appear to allow manually defined `custom_attributes`.

Our other agents use `custom_attributes` terminology, so not sure if we stick with that name, or the fact that `add_attribute` does more than what `custom_attributes` does elsewhere and we use that instead.

Thoughts, Ideas?

cc/ @bpschmitt @haihongren @ardias @thezackm

**Comment by bpschmitt** [comment]
Tough one.  I think I like `add_attribute` because it's quite clear as to what its purpose is - it just needs to support manually defined attributes.  Using `custom_attributes` could get confusing considering everything created by Flex is essentially a custom attribute on a custom event, so why do we need to add more custom attributes - but maybe I'm overthinking it :)
